### ISSUE TITLE
Code sign certificate not found?

### ISSUE THREAD

**Issue by jiajianng** [DanTheMan827/ios-app-signer#10]
Yesterday, 21 hours ago, I was able to create signed IPAs to side load. Now, I can't seem to get my signing cert anymore. How to fix?

**Comment by Marvin91** [comment]
same problem, certs are still in "~/Library/MobileDevice/Provisioning Profiles/"

**Comment by jiajianng** [comment]
No I meant signing certs not the provisioning ones.

**Comment by Marvin91** [comment]
sorry, I didn't understand.
however, I also have the same problem...

**Comment by Marvin91** [comment]
maybe same problem of #9

**Comment by kylecouillard** [comment]
Same problem here, the app says "No codesigning certificates found!" any solution out there?

**Comment by iN420KungFuYa** [comment]
2/15/2016 7:50 pm EST
Just wondering has a solution been found 4 your great iOS signing app beside installing the renewal certificate from Apple? I've downloaded & installed the certificate, also reinstalled Xcode & your iOS app signing app but when I launch your app it will say "No codesigning certificates found!" Any help would be greatly appreciated Thx, N4WR2M0!

**Comment by DanTheMan827** [comment]
This isn't a problem with iOS App Signer...

The problem is that the system no longer trusts your code signing certificates because it THINKS the signing authority has expired

If installing the updated one doesn't work you can manually go into Keychain and change the iPhone Developer certificates to always be trusted and that will make them show up in iOS App Signer again

**Comment by iN420KungFuYa** [comment]
No sir Live in Bronx NY

**Comment by iN420KungFuYa** [comment]
Ok Brother Thx that method worked 4 sure! N4WR2M0

**Comment by jiajianng** [comment]
Okay it appears to fix, you need to go into Keychain Access and search iPhone. Find the one with your Apple ID email and double click it. Then click on the first selection box and select Always Trust. Done! Found this out myself while I tried to move from iCloud Keychain to 1Password. Now close this issue someone I'm using CodeHub thanks!
