### ISSUE TITLE
Resigning changes keychain-access-groups

### ISSUE THREAD

**Issue by iAppDeveloper88** [DanTheMan827/ios-app-signer#103]
Can you please explain the reason for commit 73f30c64c4eaca370d9e7646be16716740f19b51 "The development certificate is kept consistent with the entitlements.plist file generated by xcode when it is packaged, so that it cannot be debugged after re-signing."?

Currently we are facing issues with this code change.

We are using one wildcard entry in keychain-access-groups (XXXXXX.*) with the bundle identifier (com.some.bundleidentifier). Now on resigning we are changing the bundle identifier to com.someother.bundleidentifier. Works everything fine except that the wildcard entry in keychain-access-groups gets changed to XXXXXX.com.some.bundleidentifier.

Is this an expected behavior? In our opinion this is a bug

**Comment by Coledunsby** [comment]
I am having the same issue.

**Comment by DanTheMan827** [comment]
This definitely is a bug, I've reverted this commit
