### ISSUE TITLE
Shouldn't the latest release have been 1.13 instead of 1.2 ?

### ISSUE THREAD

**Issue by alkama** [DanTheMan827/ios-app-signer#104]
Hello,

Just a note :D
I think the latest release version number 1.2 is < to the previous 1.12
Should have probably been 1.13, or 2.0 ?

**Comment by DanTheMan827** [comment]
Oh, whoops, I guess you're right... that'll have to be fixed...

**Comment by DanTheMan827** [comment]
I'll push out a revised build later today, not sure how I made that mistake to be honest...

**Comment by alkama** [comment]
Happens to the bests! Part of the fun of being humans :D

**Comment by DanTheMan827** [comment]
Released a fixed and properly versioned build
