### ISSUE TITLE
No codesigning certificates found!

### ISSUE THREAD

**Issue by natemac** [DanTheMan827/ios-app-signer#11]
Whenever I try to launch the program I get that error.
I've attempted to use Xcode with 3 different (free)Apple IDs even creating a new one. What am I missing?
Thanks for any help.

**Comment by DanTheMan827** [comment]
See #10, and #9

**Comment by natemac** [comment]
Thank you, sorry I didn't look in Closed issue for some reason. I've been pulling out my hair on this one. Thanks again.

**Comment by DanTheMan827** [comment]
One thing though, delete the old Apple Worldwide Developer Relations from both your login and system keychains before you install the updated one
