### ISSUE TITLE
Is it possible to resign an IPA without change the bundle id?

### ISSUE THREAD

**Issue by buptwsg** [DanTheMan827/ios-app-signer#110]
Hi,
I have one enterprise certificate signed IPA file, and I want to resign it with another enterprise certificate, but I don't want to change the bundle id. So for the 'Provisioning Profile' option, I choose 'Re-Sign Only'. The resign is successful, but new IPA couldn't be installed onto device.

Does this app support my requirement? 

Please help me, thanks!

**Comment by buptwsg** [comment]
Hi DanTheMan827,
Thanks for your help. I tried to create a wildcard provision profile, but when the type is Distribution / In House, only explicit app ids are list in the drop box. So I can't create such provisioning profile.

Do you have any idea? Thanks.

**Comment by DanTheMan827** [comment]
it seems apple doesn't allow distribution with a wildcard identifier, you'll need to use ad-hoc distribution if you want to be able to use a wildcard identifier.

**Step 5: Release your app to users within your organization**
If you have the Account Holder or Admin role, follow the same steps to distribute to registered devices except you don’t need to register devices before you export your app. When you export the app, select the Enterprise distribution method. Note that you can’t distribute an enterprise app using a wildcard App ID.
