### ISSUE TITLE
Retroarch on tvOS 13 - cores failed to load - Signing issue?

### ISSUE THREAD

**Issue by URBANsUNITED** [DanTheMan827/ios-app-signer#111]
Hi!

Maybe I am doing wrong, but I believe we can’t sign Retroarch for tvOS to successfully load the emulator cores.
The app itself is loading fine, but the cores fail to load.
I’ll get no errors while signing. Looks like that the cores even get signed.
Link to the latest official stable:
https://buildbot.libretro.com/stable/1.7.8/apple/tvos/RetroArch-tvOS.ipa

Tried only latest version 1.13 on macOS Catalina, latest public beta and Xcode 11 beta 7, ATV4k with latest tvOS 13 beta
I am no programmer, but willing to help!
Using a paid developer account, have also Custom Entitlements - “Some apps require special entitlements to function properly, such as the Multipath entitlement for the Houdini and Electra jailbreaks.”

Thanks

URBANsUNITED

**Comment by URBANsUNITED** [comment]
I‘ll Close this issue as it is no signing problem.
https://github.com/libretro/RetroArch/issues/9397#issuecomment-526916543

**Comment by MDOBreno** [comment]
SOLVED!

I've read about compiling for tvOS, and successfully recompiled the most part of the cores for the tvOS 13 RetroArch, and here it is:

https://mega.nz/#!QlQB0ayb!3IETCIWtCunCz39sGapiPToFprLEtvSruXZZLkCKfjs
