### ISSUE TITLE
invalid stub executable

### ISSUE THREAD

**Issue by sqig** [DanTheMan827/ios-app-signer#137]
Hello Dan,
I have used your app signer for a few years. 
Recently when signing photo and videos iOS app with my developers certificates they will not install, Im getting a invalid stub executable error.
Other iOS apps sign and instal perfectly.
Is there a way I can fix this ?
Thank you

**Comment by Dershowitz011** [comment]
Off topic. I can try signing the ipa and checking  if you don't mind.

**Comment by sqig** [comment]
> Off topic. I can try signing the ipa and checking if you don't mind.

This is one of the ipas
https://dailyuploads.net/43secnmarv17
Thank you

**Comment by Dershowitz011** [comment]
I could sign and install and run it just fine. I signed with my private script.

**Comment by sqig** [comment]
I must be doing something wrong.
Half of the iOS apps I sign work ,and all of the tvOS ones.
Can you share your script ? Is it an alternative to iOS signer ?
Thank you

**Comment by Dershowitz011** [comment]
I can sign n give you if you’re willing to share your certificate and provisioning profile. No. It is not an alternative. It’s my own one. Separate.

**Comment by sqig** [comment]
Thank you but no need I have found thst if I use the 1.10 version of ios app signer it works perfectly.
