### ISSUE TITLE
CFBundleExecutable specifies a file that is not executable

### ISSUE THREAD

**Issue by MacHanX** [DanTheMan827/ios-app-signer#14]
When i try to resign other ipa,Xcode prompt me that "CFBundleExecutable specifies a file that is not executable"  ,who can tell me why?please

**Comment by DanTheMan827** [comment]
Generally that shows up when the executable doesn't contain a image for your device CPU architecture.

What is it that you're trying to sign?

**Comment by MacHanX** [comment]
A game from my classmate,it's only had a jailbreak edition,also I try resign surge,it give me the same prompt,my Xcode version is 7.2.1 ,iPhone is 9.3,when I sign 9.2.1 Xcode didn't give me this prompt, is it the problem about iOS9.3 ? Sorry about my english poor 😅

**Comment by DanTheMan827** [comment]
v1.8.1 should fix this issue, could you please verify?
