### ISSUE TITLE
iOS 14 beta 3

### ISSUE THREAD

**Issue by upup666** [DanTheMan827/ios-app-signer#142]
Signing not working on this version of iOS

**Comment by slashboxxx** [comment]
Can confirm. Apple changed codesigning verification.

**Comment by Dershowitz011** [comment]
OS 14 b3 requires the CodeDirectory version to be updated.

iOS 14 requires a minimum CodeDirectory compatibility version of 0x00020400 to launch/install apps.

 
 Hope this helps you make required changes:

`[UPP2C3AB1D8/com.sibche.new] Notifing clients of the failed install with error: Error Domain=IXUserPresentableErrorDomain Code=1 "This app could not be installed at this time." UserInfo={NSLocalizedDescription=This app could not be installed at this time., NSLocalizedFailureReason=Could not install at this time., NSLocalizedRecoverySuggestion=Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.QXZxD7/extracted/Payload/XXXX.app : 0xe8008029 (The code signature version is no longer supported.), NSUnderlyingError=0x13089ded0 {Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.QXZxD7/extracted/Payload/XXXXX.app : 0xe8008029 (The code signature version is no longer supported.)" UserInfo={NSLocalizedDescription=Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.QXZxD7/extracted/Payload/XXXXXX.app : 0xe8008029 (The code signature version is no longer sup`

for more information:
https://twitter.com/altstoreio/status/1286095962767728645?s=21

**Comment by upup666** [comment]
> OS 14 b3 requires the CodeDirectory version to be updated.
> 
> iOS 14 requires a minimum CodeDirectory compatibility version of 0x00020400 to launch/install apps.
> 
> Hope this helps you make required changes:
> 
> `[UPP2C3AB1D8/com.sibche.new] Notifing clients of the failed install with error: Error Domain=IXUserPresentableErrorDomain Code=1 "This app could not be installed at this time." UserInfo={NSLocalizedDescription=This app could not be installed at this time., NSLocalizedFailureReason=Could not install at this time., NSLocalizedRecoverySuggestion=Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.QXZxD7/extracted/Payload/XXXX.app : 0xe8008029 (The code signature version is no longer supported.), NSUnderlyingError=0x13089ded0 {Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.QXZxD7/extracted/Payload/XXXXX.app : 0xe8008029 (The code signature version is no longer supported.)" UserInfo={NSLocalizedDescription=Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.QXZxD7/extracted/Payload/XXXXXX.app : 0xe8008029 (The code signature version is no longer sup`
> 
> For more info:
> https://twitter.com/altstoreio/status/1286095962767728645?s=21

Okay thx, will try my best to change it..

**Comment by upup666** [comment]
So Im not a supper developer, can you please change, what need to be change or make a better instruction please

**Comment by Dershowitz011** [comment]
@DanTheMan827 please make necessary modifications to the tool and also update the `shell-script.sh` to the latest version please. Thanks.

**Comment by DanTheMan827** [comment]
Are you using the corresponding version of Xcode for the beta as well?

AltStore uses a standalone codesigning tool, iOS App Signer uses the one bundled with whatever Xcode version you have installed

**Comment by upup666** [comment]
> Are you using the corresponding version of Xcode for the beta as well?
> 
> AltStore uses a standalone codesigning tool, iOS App Signer uses the one bundled with whatever Xcode version you have installed

Im trying to use both Xcode and Xcode beta to compile your app, Im also have a Developer Account. But I don't understand what I need to change, so your app signer would work

Thx for fast replying

**Comment by upup666** [comment]
So as I understand I sign apps with your app , and then import them through Impactor?

**Comment by DanTheMan827** [comment]
You would sign them with the app then install them through Xcode.

Which version of the developer tools do you have installed? the ones from the beta Xcode or the stable Xcode?

**Comment by upup666** [comment]
I have both

**Comment by upup666** [comment]
Or I can should install through configurator? I want to install not my app(YouTube++)

**Comment by upup666** [comment]
So I can use your version sign my apps and then install through Xcode?

**Comment by upup666** [comment]
> You would sign them with the app then install them through Xcode.
> 
> Which version of the developer tools do you have installed? the ones from the beta Xcode or the stable Xcode?

Thx for reply

**Comment by slashboxxx** [comment]
> You would sign them with the app then install them through Xcode.
> 
> Which version of the developer tools do you have installed? the ones from the beta Xcode or the stable Xcode?

Don't want to annoy you, but should we expect the fix for iOS 14 beta 3 soon? Thank you.

**Comment by slashboxxx** [comment]
@DanTheMan827 Don't want to annoy you, but should we expect the fix for iOS 14 beta 3 soon? Thank you.

**Comment by upup666** [comment]
@DanTheMan827  Yes everyone would be grateful

**Comment by slashboxxx** [comment]
@upup666 if you are on beta3, and have an urge to sideload, just downgrade to beta 2, using u3tools. Without losing your data. Apple is still signing beta2.

**Comment by DanTheMan827** [comment]
I just tested code signing and installing an app onto an iOS 14.0.1 device with the latest Xcode on Catalina and it installed without any error, this would lead me to believe that all you need to do is have the latest version of Xcode to get the new code signature version.
