### ISSUE TITLE
Can you write an example about how to use the shell script?

### ISSUE THREAD

**Issue by Sn0wCooder** [DanTheMan827/ios-app-signer#15]
e.g `./app-sign.sh /path/to/app.ipa ....`

**Comment by Sn0wCooder** [comment]
`/Users/Leonardo/Desktop/.temp/app-sign.sh /Users/Leonardo/Desktop/.temp/app/app.ipa "iPhone Developer: mail@gmail.com (xxxxxxxx)" /Users/Leonardo/Desktop/.temp/provision.mobileprovision`

![When I try to install](https://cloud.githubusercontent.com/assets/13628230/14403142/92bf3c62-fe4c-11e5-914e-8ccc40997fc2.png)

**Comment by DanTheMan827** [comment]
The shell script while it works for basic stuff does not support apps with extensions.

The shell script is more so here for history and I just never got around to removing the download link
