### ISSUE TITLE
Codesigning error

### ISSUE THREAD

**Issue by joedee** [DanTheMan827/ios-app-signer#16]
I'm getting the following error when trying to run the app signer:

> Codesigning error
> 
> You appear to have a error with your codesigning certificate, do you want me to try and fix the problem?

I'm running El Capitan and XCode 7.3 with a free Apple Developer account. Version 1.8 of iOS App Signer.

Tried running the fix option but not effective.

<img width="422" alt="screen shot 2016-04-10 at 5 55 02 pm" src="https://cloud.githubusercontent.com/assets/1358339/14413790/c2ced51e-ff52-11e5-9aed-8055f8b2360e.png">
<img width="422" alt="screen shot 2016-04-10 at 5 55 15 pm" src="https://cloud.githubusercontent.com/assets/1358339/14413789/c2cd05a4-ff52-11e5-9c83-daceb2eb8432.png">

**Comment by DanTheMan827** [comment]
If you o into keychain and then view your signing certificate does it have any error by it?

**Comment by joedee** [comment]
No it looks good.

![certs](https://cloud.githubusercontent.com/assets/1358339/14413847/3561cf4a-ff54-11e5-9261-32289765e315.jpg)

Probably connected; I do get an error when I try to add a new App Group in XCode:

<img width="553" alt="screen shot 2016-04-10 at 7 41 44 pm" src="https://cloud.githubusercontent.com/assets/1358339/14413838/20d41e70-ff54-11e5-92a6-46ad7f4b2a05.png">

And when I try to run the project in XCode:

<img width="421" alt="screen shot 2016-04-10 at 7 42 05 pm" src="https://cloud.githubusercontent.com/assets/1358339/14413844/2e427566-ff54-11e5-8614-9c36081b1070.png">

**Comment by DanTheMan827** [comment]
The blue circle with the plus in keychain means that the certificate was manually trusted

Open the properties for your certificate and change the Trust type from "Always trust" to the system default

That should fix the signing certificate issue

Although, it seems like you may have other certificate issues than just the signing certificate... Is your system clock correct?

**Comment by joedee** [comment]
Ya I'd manually changed to see if that would change anything. I set back to System Defaults and same result. System clock is set automatically, so yes that should be fine.

**Comment by DanTheMan827** [comment]
And after it was set back to System Defaults it didn't report an error in keychain at all?

What you can try is to delete the account from Xcode, then go into Keychain and delete the certificate.

Then when you sign back in to Xcode it will ask you if you want to reset the signing certificate.

You will have to re-sign any apps you may have successfully signed before (if any)

Also, if you do that the existing provisioning profiles will no longer be valid... those can be found at ~/Library/MobileDevice/Provisioning Profiles (you can use Command+SHIFT+G in Finder to easily go there)

Just delete the files in that folder (Xcode will re-download them as needed)

**Comment by joedee** [comment]
Tried this too but no luck.

Worth noting that in version 1.7 I get the "Error processing deb file" and in version 1.8 I get the codesigning error.

**Comment by owen161** [comment]
Im using 1.8, follow all the steps through x-code to obtain the certificate and provisioning profiles and the application runs with no errors, however when I attempt to install the app through the devices method it fails with the message, App Installation Failed, The application does not have a valid signature. It is the same response I get if I hadn't used your IOS App signer software.

**Comment by Furnan** [comment]
Hi,

Same issue here.

I'm running El Capitan with a free Apple Developer account. Version 1.8 of iOS App Signer.

Tried running the fix option but not effective.

**Comment by Sn0wCooder** [comment]
Same problem

**Comment by Sn0wCooder** [comment]
Plz help me

**Comment by adriannabarro** [comment]
Hello

I'm having this issue on macOS Sierra. Happy to contribute however I can.

**Comment by adriannabarro** [comment]
Hello again.

I'm still seeing this using the latest version (1.8.2).

**Comment by Beachiie** [comment]
Hi there, I also experience the same problem with OS Sierra and the iOS App Signer 1.8.2

Please advise..

**Comment by LissChonoplis** [comment]
I found this on the internet and I worked:

**This was caused by a certificate that expired,
You have to delete the expired certificate from keychain before you install the new one.**

**Comment by x4vl** [comment]
Same here with no expired certificates...

**Comment by True-Design** [comment]
Im getting the same issue aswell. I have tried everything you mentioned but no luck. Any suggestions?

**Comment by maclamont** [comment]
I have the same issue.  Deleting the certificate and changing the trust settings doesn't do anything

**Comment by kmddd59** [comment]
SecKey API returned: -67808, (null)/var/folders/gm/nwvzn56j3t1cchmltp0t5p380000gn/T/com.DanTheMan827.AppSigner.CPPhiLOk/out/Payload/FreeDyn.app: invalid signature (code or signature have been modified)
In architecture: armv7

i have attached the files below I'm using all latest stuff and i get that error above this is the first time i have seen this so i don't know what is happening here

[Archive.zip](https://github.com/DanTheMan827/ios-app-signer/files/453197/Archive.zip)

**Comment by adriannabarro** [comment]
Sad to report this issue is still in in 1.8.3.

**Comment by kmddd59** [comment]
@DanTheMan827 I'm contacting u here because i can't seem to find any other way id like to see if there is a way to allow resining iOS apps that use apple watch apps to work it seems to me every time I'm on the resigner it won't send the watch app through even if i use iTunes and I'm jailbroken so i thought maybe thats why so i got my other phone nope thats not it so i got the jailbroken one and got the app sync to allow unsigned code nope no go can u help?

**Comment by orchiha** [comment]
Has this been resolved yet? I am having the same issue running with OS 10.9.

**Comment by ike185** [comment]
Same problem at my end.

**Comment by chourobin** [comment]
Hey all, I got it working for me. I was running into the same issues described above. I suspect my problem was I had duplicate identities (i.e. certificates) in my keychain. Here's how I resolved:

- Go into Keychain and delete all the related certificates
- Quit Xcode, Re-launch Xcode and let it automatically download the certs again
- Go through iOS App Signer steps (making sure you choose the correct signing identity and the matching provisioning profile via app identifier)

Works smoothly thereafter. Good luck.

**Comment by tixastronauta** [comment]
@chourobin That was it! It also worked for me. Thank you very much!

**Comment by greeneggswitspam** [comment]
@chourobin did you delete all of your certificates? I deleted 1 duplicate I had but it still isn't working for me.

**Comment by Beachiie** [comment]
Still isn't working for me.. And I've tried everything.

**Comment by ady199** [comment]
Same problem for me and I've deleted all my certificates!

Help!!!!!

**Comment by ike185** [comment]
Yep, also the same at my end. I gave up till a fresh idea to try out comes my way.

**Comment by light122** [comment]
I have the same issue with "codesigning error". I have a $99 paid developer membership. I performed all the steps recommended in DanTheMan827 steps below, but the issue persists. Is there a way to fix this? I am trying to reload Kodi onto my iPAD after upgrading to IOS 10.0.2 (and Mac to Sierra), as it no longer works. Thanks for any help available.

DanTheMan827 recommended steps from another entry:
Go into Xcode and delete your account from Preferences

Go to ~/Library/MobileDevice/Provisioning Profiles in finder and delete the files within

Go into keychain and delete any personal certificates mentioning Mac Developer, iOS Developer, etc

Add your account back into Xcode and choose to revoke the existing certificate

You'll have to re-generate any provisioning profiles since the previous ones were tied to the now revoked certificate and are now invalid

And also, don't manually trust the developer certificates... that breaks code signing completely since codesign won't trust it..

**Comment by DanTheMan827** [comment]
Try opening terminal and run the following command

    xcode-select --install

**Comment by light122** [comment]
Brilliant!!!  You are my hero.  Why did this work, i.e., what was the “hangup”?  Thanks again.

**Comment by ike185** [comment]
@light122 Thanks! Your solution worked for me. Am back on.

**Comment by greeneggswitspam** [comment]
@light122 @DanTheMan827 worked for me as well ! I'm back watching movies and shows on kodi!!

**Comment by DanTheMan827** [comment]
@light122 Sorry, I've just been busy with other things...

I'm guessing a MacOS system update/upgrade removed the Xcode developer tools or that they were never installed...

That command tells the system to install them

**Comment by Beachiie** [comment]
This is very frustrating as I did everything according to @light122 and @DanTheMan827. I still got the same error result. Can anyone please tell me what has gone wrong? 
![screen shot 2016-10-12 at 10 27 20](https://cloud.githubusercontent.com/assets/20565192/19304935/8c6476c8-9066-11e6-8d5e-4ba314d78590.png)
![screen shot 2016-10-12 at 10 27 41](https://cloud.githubusercontent.com/assets/20565192/19304942/958ec294-9066-11e6-83f0-ea7468d73313.png)

**Comment by ike185** [comment]
Yeah you know what. I spoke too soon. Tried to sign another app and getting the same error too. Tried @light122 solution which worked the first time and still getting the same error. Very frustrating indeed.

**Comment by Brak01** [comment]
When I click start it starts to process the ipa, but then I get the following error:

ERROR VERIFYING CODE SIGNATURE!
/var/folders/w7/h7_kf9191ts1bjth93rl7y700000gn/T/com.DanTheMan827.AppSigner.attQNDYW/out/Payload/Test App.app: invalid Info.plist (plist or signature have been modified)
In architecture: armv7

I am even trying this on an app I copied from my phone and running it without doing any modifications to it, but still getting the same error.

Any advise how to resolve this issue?

**Comment by onekeyghost** [comment]
I met the same problem.I reset the certification but
![image](https://cloud.githubusercontent.com/assets/11979927/22349069/03b5d5b0-e449-11e6-929c-072bd6c2e452.png)

**Comment by johnalex731** [comment]
Yup, getting the same problem, tried EVERY "Solution" I can find, with no luck

**Comment by Brak01** [comment]
WIll Dan ever reply to this?

**Comment by wangdetong** [comment]
@Brak01 The problem that I have ever had.Reason is that when I test `injection dylib`, I didn't change the debug package to release package.Just change to release package is OK

**Comment by DanTheMan827** [comment]
@Brak01 Honestly, my app is just a GUI to the codesign command line utility.

If that's having problems signing a working app, my app won't magically make it work...

I've tested the app on all the OS versions I can think of, but it works every time...

The problem is almost always due to a misconfigured certificate or caused by selecting a mismatched certificate / provisioning profile pair...

I want to help, but short of hopping onto a computer with a problem for a more in-depth look, I can't re-create it...

**Comment by ginobean** [comment]
In my case, when I went into 'Keychain Access', under 'My Certificates', I noticed that I had a bunch of expired certificates. When I deleted all of the expired certificates under 'My Certificates', the iOS App Signer was able to work. You may want to add logic to your 'iOS App Signer' to skip over the expired certificates, as I think what may be happening is that your app is picking the first match, but this first match may actually be an expired certificate. 

Xcode doesn't have a problem with this, suggesting that Xcode is automatically ignoring the expired certificates.

**Comment by zhao15** [comment]
I did everything according to above. I still got the same error result.

**Comment by frozt** [comment]
I had the same problem followed @ginobean comment and worked.

**Comment by jacrave** [comment]
The same error was being thrown for me. The issue was that I had 2 certificates, both valid, but upon further examination I found that 1 was revoked. I just had to delete it and then poof!, re-sign worked like a charm.

**Comment by fragno** [comment]
@chourobin cool, problem solved

**Comment by Joshab1177** [comment]
I have gone through multiple pages and followed all directions and nothing seems to work. I am running version 1.10 of App Signer, Version 10 of Xcode, and MacOS 10.13.6.

Xcode works all day long as far as detecting my certs. When I get to App Signer though it fails. Only thing I didn't try was the terminal command.

![image](https://user-images.githubusercontent.com/43612787/46088065-a0eeac80-c179-11e8-8482-5cfe59adf896.jpg)
![image-1](https://user-images.githubusercontent.com/43612787/46088068-a3510680-c179-11e8-9090-3646bc7a3241.jpg)
![image-2](https://user-images.githubusercontent.com/43612787/46088073-a5b36080-c179-11e8-9d4a-84cbd2ab334b.jpg)
![image-3](https://user-images.githubusercontent.com/43612787/46088079-a77d2400-c179-11e8-80a0-525cbf4f0bbd.jpg)

**Comment by wessidetempest** [comment]
So I deleted certs that were outdated and were not relevant anyway. All o the remaining My Certificates and Certificates have expiration dates in the future and are set to Trust: System Default. 
The only certification that I question has my name (global user name for computer) and the warning says: "This certificate has not been verified by a third party".  Is that the potential issue?

**Comment by AdamMeyerTech** [comment]
I just wanted to say I am a complete noob at this and I just created an account to tell everything this process DOES work. Thank you so much!! 

There was some fiddling around and the "+" on the last step isnt clear which "+" but on the whole it works.

THANK YOU DAN!!!!!

**Comment by DocileWolf2786** [comment]
I had the code signing error and tried to follow the instructions to delete old certain and provisioning profiles, but now I think I deleted something I wasn’t supposed to because every time I try to sign an app, iOS App Signer crashes. Please help!

**Comment by mdiazm** [comment]
> Try opening terminal and run the following command
> 
> ```
> xcode-select --install
> ```

Brilliant!!!!

**Comment by xiaojiakai** [comment]
> Try opening terminal and run the following command
> 
> ```
> xcode-select --install
> ```

thx bro, u saved my day

**Comment by geekygreek7** [comment]
FIXED SIGNING ISSUE!
(spent HOURS trying to fix this, and tried TONS of variations with only small changes to each variation)

Steps:
1. Open Keychain Access
2. Delete ALL certs in login and system (for keychains) and in Certificates and My Certificates under Category (left bottom)
3. Quit Xcode, Opened Xcode. Went to Xcode > Preferences > (made sure I was signed in), Highlighted the apple ID on the left, then highlighted the Team name on the bottom right, then clicked Manage Certificates. Clicked the + sign then iOS Development. I then noticed it added my cert in the keychain app which was running in the background.
4. Downloaded: https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer (from https://developer.apple.com/support/expiration/) Opened it and it suddenly changed my cert in Keychain from untrusted to "This Certifcate is valid". 
5. Opened iOS App Signer then selected my input file, then selected the Signing Cert (which had one choice), selected my Provisioning Profile.
6. Clicked START and DONE!

**Comment by 5UFKEFU** [comment]
> FIXED SIGNING ISSUE!
> (spent HOURS trying to fix this, and tried TONS of variations with only small changes to each variation)
> 
> Steps:
> 
> 1. Open Keychain Access
> 2. Delete ALL certs in login and system (for keychains) and in Certificates and My Certificates under Category (left bottom)
> 3. Quit Xcode, Opened Xcode. Went to Xcode > Preferences > (made sure I was signed in), Highlighted the apple ID on the left, then highlighted the Team name on the bottom right, then clicked Manage Certificates. Clicked the + sign then iOS Development. I then noticed it added my cert in the keychain app which was running in the background.
> 4. Downloaded: https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer (from https://developer.apple.com/support/expiration/) Opened it and it suddenly changed my cert in Keychain from untrusted to "This Certifcate is valid".
> 5. Opened iOS App Signer then selected my input file, then selected the Signing Cert (which had one choice), selected my Provisioning Profile.
> 6. Clicked START and DONE!

Thank you,It's work for me.

**Comment by sourabhtokkar** [comment]
> FIXED SIGNING ISSUE! (spent HOURS trying to fix this, and tried TONS of variations with only small changes to each variation)
> 
> Steps:
> 
> 1. Open Keychain Access
> 2. Delete ALL certs in login and system (for keychains) and in Certificates and My Certificates under Category (left bottom)
> 3. Quit Xcode, Opened Xcode. Went to Xcode > Preferences > (made sure I was signed in), Highlighted the apple ID on the left, then highlighted the Team name on the bottom right, then clicked Manage Certificates. Clicked the + sign then iOS Development. I then noticed it added my cert in the keychain app which was running in the background.
> 4. Downloaded: https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer (from https://developer.apple.com/support/expiration/) Opened it and it suddenly changed my cert in Keychain from untrusted to "This Certifcate is valid".
> 5. Opened iOS App Signer then selected my input file, then selected the Signing Cert (which had one choice), selected my Provisioning Profile.
> 6. Clicked START and DONE!
---------------------------
Man !!!
You saved my day, I struggled for atleast 4 hours to fix the issue. After following your steps, it worked like charm.

**Comment by wyatt8740** [comment]
My experience: For whatever reason, I somehow had two identical signing certificates installed, and that was throwing the program off in my case. Make sure you don't do that.

**Comment by bmsimo** [comment]
I've had the same issue. I was importing my certificate to the system keychains. I've fixed doing these steps:
1. Deleting the certificate from "System Keychains"
2. Importing to login keychain.

**Comment by ColonelXing** [comment]
来信已收到！我会尽快回复。
