### ISSUE TITLE
Error  failed to get pid for label UIKitApplication 

### ISSUE THREAD

**Issue by hebiao6446** [DanTheMan827/ios-app-signer#172]
OS : Catania 10.15.4 
Xcode： 12.2
IPhoneOS ： 13.6   6s Plus 

Signed OK
Install  OK 
Launch  OK  
A few seconds later , CRASH  !!!!!!     I got ERROR  at APP launch .  

HERE the log from iPhone. 

Jan 15 15:44:15 iPhone-plus-hebiao runningboardd(RunningBoard)[28] <Error>: failed to get pid for label UIKitApplication:com.test.app[058b][rb-legacy] : No such process (3)
Jan 15 15:44:15 iPhone-plus-hebiao runningboardd(RunningBoard)[28] <Error>: Failed to start job for application<com.naviguy.ar>: <NSError: 0x119de9550; domain: NSPOSIXErrorDomain; code: 3; reason: "No such process"> {
    userInfo = {
        RBLaunchdOperation = launch_get_running_pid_4SB;
        RBLaunchdJobLabel = UIKitApplication:com.test.app[058b][rb-legacy];
    }
}
Jan 15 15:44:15 iPhone-plus-hebiao SpringBoard(FrontBoard)[55] <Error>: Bootstrapping failed for <FBApplicationProcess: 0x115fcdd40; application<com.test.app>:-1> with error: <NSError: 0x280f09110; domain: RBSRequestErrorDomain; code: 5; reason: "The launchd job couldn't be started."> {
    underlyingError = <NSError: 0x280f0bbd0; domain: NSPOSIXErrorDomain; code: 3; reason: "No such process"> {
        userInfo = {
            RBLaunchdOperation = launch_get_running_pid_4SB;
            RBLaunchdJobLabel = UIKitApplication:com.test.app[058b][rb-legacy];
        }
    };
}

**Comment by DanTheMan827** [comment]
Without any source code it's not really possible to debug this.
