### ISSUE TITLE
Error processing deb file

### ISSUE THREAD

**Issue by Ademzz** [DanTheMan827/ios-app-signer#23]
I keep getting this "error processing deb file" on almost every deb file. and i wonder if i can fix it some way

![skarmavbild 2016-06-30 kl 15 41 50](https://cloud.githubusercontent.com/assets/20226348/16519562/4db8b3ee-3f8a-11e6-8eab-968562f66672.png)

**Comment by DanTheMan827** [comment]
Could you please post the application log? (View > Application Log)

**Comment by Ademzz** [comment]
![skarmavbild 2016-06-30 kl 16 06 12](https://cloud.githubusercontent.com/assets/20226348/16491078/c565c192-3edc-11e6-927e-da520edae29c.png)

**Comment by Ademzz** [comment]
![skarmavbild 2016-06-30 kl 16 09 45](https://cloud.githubusercontent.com/assets/20226348/16491159/18816dea-3edd-11e6-924a-96261303d55b.png)
 
Maybe this is the problem

**Comment by Ademzz** [comment]
![skarmavbild 2016-07-01 kl 12 56 35](https://cloud.githubusercontent.com/assets/20226348/16519715/49391f7e-3f8b-11e6-8168-8fc260ea9d86.png)

**Comment by DanTheMan827** [comment]
Which deb are you trying to sign?

If it's a jailbreak tweak it may not work...

There needs to be a Applications folder inside of the .deb file or the application would in fact give that error...

The application is failing when it tries to move the Applications folder from the extracted deb file to the working directory.
