### ISSUE TITLE
App Signer Doesn't update new provisional profiles

### ISSUE THREAD

**Issue by USMCPerezRo** [DanTheMan827/ios-app-signer#25]
I can create new projects within Xcode, (I am a paid developer), and the names won't pop up inside the provisional profile list. I've opened and closed it, downloaded all the certificates, uninstalled and reinstalled Xcode as well the the signer app. Please help?

**Comment by DanTheMan827** [comment]
Please post the application log

**Comment by USMCPerezRo** [comment]
Sorry about the delay.
![log](https://cloud.githubusercontent.com/assets/20467717/16897539/356fb31a-4b69-11e6-9445-09a76026ee11.png)

**Comment by DanTheMan827** [comment]
Does nothing show in iOS App Signer?

This says that it added four profiles with * as the app identifier (which is valid for anything)

**Comment by USMCPerezRo** [comment]
What I've been doing, not sure if it's right or not, that for every new device I do, I create a new project in Xcode, the new project will show up and then it modifies the deb and the app installs. If I tried to use the same modified for another device it wouldn't work so I created a new project every time. Now when I create a new project it doesn't show up in app signer and I'm not able to install the modified file into my device.

Respectfully,
Joshua Perez-Roberts

**Comment by USMCPerezRo** [comment]
Okay I got it to work once, I redownloaded the the provisional, created new project and was able to push it to my iPad pro. Then following that I received and error on both my MacBook Pro and iMac 

![log](https://cloud.githubusercontent.com/assets/20467717/16898110/3c9d4bd8-4b7e-11e6-9984-9d09be66e3f1.png)

**Comment by DanTheMan827** [comment]
May I ask what you are trying to sign?

**Comment by USMCPerezRo** [comment]
Yea I’m trying to sign Kodi. I’m seeing everything is going through except when I use “iPhone developer” I get the error. I’ve checked to make sure the “trust” is on “system preference” I’ve deleted the files from the access and Xcode and redownload them and I just keep getting the error.
It did work the one time but now it won’t pass this.

Respectfully,
Joshua Perez-Roberts

**Comment by USMCPerezRo** [comment]
I downloaded the file and if I keep clicking to install after each use it. I usually get an error verifying code signature now.

**Comment by USMCPerezRo** [comment]
Fixed. Deleted all the certificates in the "portal" file and then re downloaded everything and works great. Thanks
