### ISSUE TITLE
this app does not work with tvos17

### ISSUE THREAD

**Issue by TresPorCiento** [DanTheMan827/ios-app-signer#252]
I installed Sonoma 14 with Xcode 15 and tvos17. I used this app to sideload my app to tvOS 16.4 without problems but I cannot side load to tvOS 17. No way. I have the source code for this one and I could compile and install on tvOS 17. But for the others that  I do not have the source code no way I have to side load and install the ipa file. So seems the issue is the iOS signer app.

Error installing  '/Users/<userid>/Documents/Local.nosync/AppleTV/tvOSBrowser.ipa', ERROR: Error Domain=com.apple.dt.CoreDeviceError Code=3002 "Failed to install the app on the device." UserInfo={NSLocalizedDescription=Failed to install the app on the device., NSURL=file:///Users/<userid>/Documents/Local.nosync/AppleTV/tvOSBrowser.ipa, NSUnderlyingError=0x60000f766700 {Error Domain=com.apple.dt.CoreDeviceError Code=3000 "The item at tvOSBrowser.ipa is not a valid bundle." UserInfo={NSURL=file:///Users/<userid>/Documents/Local.nosync/AppleTV/tvOSBrowser.ipa, NSLocalizedDescription=The item at tvOSBrowser.ipa is not a valid bundle., NSLocalizedFailureReason=Failed to read the bundle.}}}
Domain: com.apple.dt.DVTCoreDevice
Code: -1
User Info: {
    DVTErrorCreationDateKey = "2023-10-22 08:53:58 +0000";
}
--

System Information

macOS Version 14.0 (Build 23A344)
Xcode 15.0.1 (22266) (Build 15A507)
Timestamp: 2023-10-22T05:53:58-03:00

**Comment by kingkej** [comment]
Same here. Did you find a workaround?

**Comment by kingkej** [comment]
> this is a problem strictly of Xcode 15, uploading with Xcode 14 works fine

Will give a try. Thanks.

**Comment by dmytrokoren** [comment]
The solution
A workaround for installing .ipa files on iOS devices is:
Changing the ".ipa" file extension to ".zip" Open/unzip Install the .app file located in resulting "Payload" folder instead
Then go to xCode an install the app.

credits: https://developer.apple.com/forums/thread/731240?answerId=767583022#767583022

**Comment by kambala-decapitator** [comment]
another workaround is to use Apple Configurator to upload ipa

**Comment by TresPorCiento** [comment]
now is solved with the new versions.
