### ISSUE TITLE
cannot open application

### ISSUE THREAD

**Issue by teezyyoxo** [DanTheMan827/ios-app-signer#26]
i get either of the two error messages when attempting to open the application, even after changing the file name to not include periods (so that the file isn't interpreted as a ".Signer" file instead of ".app")

1. You can’t open the application “iOS.App.Signer” because it may be damaged or incomplete.
2. You can’t open the application “iOS.App.Signer” because PowerPC applications are no longer supported.

machine specs:
13" macbook pro, mid-2012
2.9gHz i7, 16GB RAM
OS X El Capitan (10.11.5)

**Comment by DanTheMan827** [comment]
That sounds like you got a corrupt download...

I just tried downloading 1.8.2 from https://github.com/DanTheMan827/ios-app-signer/releases/download/1.8.2/iOS.App.Signer.app.zip and it opened without issue for me (also running 10.11.5)

**Comment by teezyyoxo** [comment]
I've downloaded it multiple times, and get the same result. 

Sent from my iPhone

On Jul 25, 2016, at 11:54 AM, DanTheMan827 <notifications@github.com> wrote:

Closed #26.

**Comment by DanTheMan827** [comment]
And the MD5 of iOS.App.Signer.app.zip matches?

8F4F4B8462A7C7FCAE14074383B4AD83

**Comment by teezyyoxo** [comment]
Yes, sir. Sorry for the delay. Seems as if every app I download from GitHub produces the same result. I don't understand, lol.
