### ISSUE TITLE
MacOS 15 provisioning profiles not loading

### ISSUE THREAD

**Issue by via-justa** [DanTheMan827/ios-app-signer#266]
I'm no a Mac or Swift power user but I think they changed the path where the provisioning profiles are stored in MacOS 15 and due to that the code in this block cannot find them
https://github.com/DanTheMan827/ios-app-signer/blob/6dd40849ded7464ae79ae032c8d38db584a30090/ProvisioningProfile.swift#L24C1-L38C10

The path where I can find my profiles is `~/Library/Developer/Xcode/UserData/Provisioning Profiles`

**Comment by ImNoahDev** [comment]
I have the same issue on 15.0.

**Comment by SeldomCouth** [comment]
I was able to work around this by copying my .mobileprovision file to the old location ~/Library/MobileDevice/Provisioning Profiles. Note if you do this while Xcode is running, it removes the file immediately.

**Comment by via-justa** [comment]
I just copied the profile to the same folder I store the app and use the load profile from file option. That way Xcode won't touch it. One more step I need to do every week but better than nothing

**Comment by kambala-decapitator** [comment]
just symlink new path to the old path

**Comment by tr1ckyf0x** [comment]
Fixed in #267

**Comment by phoenixray2000** [comment]
the fix failed to build a new released version
![image](https://github.com/user-attachments/assets/8b59e658-41b2-4dbe-abaa-915c0ce9a4c3)

Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

**Comment by ImNoahDev** [comment]
A working build of iOS App Signer for MacOS Sequoia can be found here: [ImNoahDev/ios-app-signer/releases/tag/1.15.0](https://github.com/ImNoahDev/ios-app-signer/releases/tag/1.15.0)
