### ISSUE TITLE
Payload directory doesn't exist

### ISSUE THREAD

**Issue by MTShare** [DanTheMan827/ios-app-signer#29]
When i try to resign an IPA that i have repacked (using Mac Compression Utility) i get this error: "Payload directory doesn't exist". 
Any suggestions? 
Obviously the Payload folder is present. 
I think is something related to the compression level used by Mac.

**Comment by DanTheMan827** [comment]
You can select the app bundle to resign and it will automatically package it inside of an IPA

There's no need to package it just to have iOS app signer unpack, sign, and re-pack

**Comment by yangshebing** [comment]
Please compress the "Payload" folder, modify the filename to X.ipa, and then re sign the IPA package

**Comment by DanTheMan827** [comment]
There’s no need to compress the app before running it through app signer,
you can open the app bundle directly

**Comment by luixiuno** [comment]
the bundle is the id like for example: com.DanTheManXD.PhoenixPwn
