### ISSUE TITLE
Problem with mac os sierra 10.12.1 Beta 3 (16B2338c)???

### ISSUE THREAD

**Issue by poipop** [DanTheMan827/ios-app-signer#30]
Hi guys! :) Is there a general problem with ios app signer and the sierra beta 3 or i have the prob? when i hit start the app crashes and i take this message! Please help me... :( 
![ios app crashed](https://cloud.githubusercontent.com/assets/22765477/19264526/b3e18f0a-8fa9-11e6-981a-136cc4acf08b.jpeg)

**Comment by DanTheMan827** [comment]
Does it still do it if you install the final release of MacOS Sierra and not the beta?

**Comment by poipop** [comment]
With the final release i had no problem... But not either with beta 1 and beta 2...! Only with beta 3...!

**Comment by DanTheMan827** [comment]
I actually haven't tested the app on a single beta release but this seems like something that will be fixed by apple or possibly require recompiling with a new version of Xcode

I'll take a look at it though

**Comment by poipop** [comment]
I have also Xcode 8.1 Beta 3... If you can take a look and tell me please how can i solve this prob... :)

**Comment by poipop** [comment]
i put today Mac os sierra beta 4 and it is not crashing but i have the "codesigning error"... Can you help me???
