### ISSUE TITLE
Huge launch time and slow re-signing

### ISSUE THREAD

**Issue by cchaine** [DanTheMan827/ios-app-signer#35]
I've an issue when launching the app. It takes a while to start and to sign

**Comment by DanTheMan827** [comment]
Do you have a lot of provisioning profiles in **~/Library/MobileDevice/Provisioning Profiles**?

The application loops through every one of those and parses them to avoid showing expired profiles in the list

**Comment by cchaine** [comment]
No, I tried with another account were I've just got one provisioning profile and it is still very slow
Could there be an issue with this profile ?
My computer as enough power

**Comment by ageorgios** [comment]
same problem with long processing times here

**Comment by cchaine** [comment]
That worked. Thanks.
