### ISSUE TITLE
ios-app-signer Crash 

### ISSUE THREAD

**Issue by codesourse** [DanTheMan827/ios-app-signer#37]
when i sign the ipa,it's crash.

**Comment by codesourse** [comment]
*** Terminating app due to uncaught exception 'NSGenericException', reason: '-[NSAlert runModal] may only be invoked from the main thread. Behavior on other threads is undefined.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff780a96fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff8c8b0a2a objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff781269a5 +[NSException raise:format:] + 197
	3   AppKit                              0x00007fff764c4937 _NSRunModal + 103
	4   AppKit                              0x00007fff75f729b9 -[NSAlert runModal] + 270
	5   iOS App Signer                      0x000000010bae36ed _TFC14iOS_App_Signer8MainView13signingThreadfT_T_ + 41037
	6   iOS App Signer                      0x000000010bae9d52 _TToFC14iOS_App_Signer8MainView13signingThreadfT_T_ + 34
	7   Foundation                          0x00007fff79a4d30d __NSThread__start__ + 1243
	8   libsystem_pthread.dylib             0x00007fff8d3a4aa

**Comment by DanTheMan827** [comment]
This is the newest version of the app?

What OS version?

**Comment by DanTheMan827** [comment]
This issue will be fixed in the next version.

In the meantime, it's crashing because it's trying to display one of these error messages.

- Input file not found
- Error verifying code signature!

The latter is more likely, make sure the correct profile / certificate pair is selected.

**Comment by codesourse** [comment]
1.8.3

**Comment by codesourse** [comment]
V10.12.1 (16B2555)

**Comment by mdbijoy069** [comment]
Nice
