### ISSUE TITLE
Unable to change application identifier with wildcard provisioning profile

### ISSUE THREAD

**Issue by DanTheMan827** [DanTheMan827/ios-app-signer#4]
IPA file won't install due to entitlements being incorrect.

I don't have a paid developer account so I don't have access to a wildcard profile.

Could someone upload one? (I don't need the signing certificate, just the profile)

**Comment by hatemalimam** [comment]
I'm also having the same problem, although mine is a paid account.
![screen shot 2015-12-18 at 23 27 15](https://cloud.githubusercontent.com/assets/3439970/11908718/fd2301c2-a5de-11e5-94f6-969deee5f159.png)

**Comment by DanTheMan827** [comment]
Could you test with this build? https://github.com/DanTheMan827/ios-app-signer/releases/download/1.0b13/iOS.App.Signer.app.zip
