### ISSUE TITLE
Valid Provisioning Profile Not Found

### ISSUE THREAD

**Issue by edstewbob** [DanTheMan827/ios-app-signer#42]
When trying add an IPM to my iPad I get the error message "A valid provisioning profile was not found for this executable." I am using Xcode 8.2.1 with App Signer 1.9 on Sierra 10.12.2. The deb I am using is for the Kodi iPad/iPhone software that lots of people have already installed. I've recreated my provisioning profiles several times and tried everything I can think of with no errors received during the App Signer run. Any ideas of were else I can look or what else to try?

**Comment by DanTheMan827** [comment]
Do you have more than one certificate available to use?

**Comment by edstewbob** [comment]
Yes I have two, I setup one for development and one for distribution and they both expire in Nov 2017. I have a valid developer's account.

**Comment by DanTheMan827** [comment]
Was the profile created with the web interface or did Xcode take care of it?

Is it possible that the device wasn't selected for that specific profile?

**Comment by edstewbob** [comment]
You caused me to take a 2nd look at the cert I was using and I selected the MAC one instead of the IOS one for the IOS App Signer. When I selected the correct IOS cert everything went fine. Thanks for your quick response.

**Comment by DanTheMan827** [comment]
Glad that I could help
