### ISSUE TITLE
remote sign using ssh

### ISSUE THREAD

**Issue by kmddd59** [DanTheMan827/ios-app-signer#43]
my developer team are having issues with this script I got my Mac up and forwarded it over ssh and gave access to the team but one of my team members found its not possible to do over ssh can you explain why or how this might be fixed

**Comment by DanTheMan827** [comment]
the shell_script branch is a old version that is just there for archival purposes..

I don't know if that works anymore to be honest...

**Comment by kmddd59** [comment]
it dose I have used it because the GUI is having issues with my Mac when I added a second user to it
I have all my signing scripts messed up and now I can only sign using this

**Comment by DanTheMan827** [comment]
It appears that the codesign command has issues running over SSH

The issue appears to be related to keychain

One solution would be to unlock the keychain before running the signing
script

See the accepted answer for this stackoverflow question

http://stackoverflow.com/questions/20205162/user-interaction-is-not-allowed-trying-to-sign-an-osx-app-using-codesign

**Comment by kmddd59** [comment]
found a fix for this `security unlock-keychain -p <YourPassword> ~/Library/Keychains/login.keychain` also removing the file extortion and moving it to /bin is handy to make it run from anywhere

**Comment by kmddd59** [comment]
`<YourPassord>` is your Mac password without the <>

**Comment by kmddd59** [comment]
fix found here [http://superuser.com/a/363840](url)

**Comment by kmddd59** [comment]
please close and update the code if possible I have no code knowledge so I don't know how to add the command into the code if you fix it let me know thanks
