### ISSUE TITLE
Resign app with PlugIns folder

### ISSUE THREAD

**Issue by mysteriouss** [DanTheMan827/ios-app-signer#48]
As far as I could test, the appex is signed with the same bundle-identifier as the main app which could lead to wrong execution of appex in PlugIns folder, apple watch appex maybe  included.

**Comment by igorkulman** [comment]
Any update on this? I added a notification extension to my app and I am having the same problem. The appex is detected, app id is changed but it is signed with the same cert and the resulting IPA cannot be installed onto a device.

**Comment by kotori2** [comment]
Same here

**Comment by freyzheng** [comment]
Same problem.

**Comment by DanTheMan827** [comment]
I believe PR #97 fixes this

It allows you to sign the plugins prior to signing the main bundle
