### ISSUE TITLE
Sign python eggs

### ISSUE THREAD

**Issue by Memphiz** [DanTheMan827/ios-app-signer#5]
Could you add a feature where it looks for *.egg files in our app bundle, extracts them (unzip) and sign the usual binaries (same as for the bundle) found in the extracted folder, then repack it to the former egg file?

If you have done this right you should be able to use the open weathermap addon on non-jailbroken devices (which should fail currently because of trying to load the unsigned pythonmodule-pil which is contained in the Pillow egg).

Would be a great addition (also for the tvos future)

**Comment by DanTheMan827** [comment]
I looked in the deb file and I couldn't find any .egg files... just some .egg-info files which are just metadata...

That said, I'm pretty sure I have a build that would properly sign them but it's just a guess until I have something to test...
[iOS App Signer.app.zip](https://github.com/DanTheMan827/ios-app-signer/files/70268/iOS.App.Signer.app.zip)

**Comment by Memphiz** [comment]
You are right - in jarvis the eggs are already extracted. But in current mainline there are egg files. The TVOS test build for example has those :)
Looks pretty good from the log:

http://pastebin.com/YTkLmg5Y

If i have read the code correctly you even try to sign eggs in eggs here right?:

https://github.com/DanTheMan827/ios-app-signer/blob/82fde2aabce4ce8d6388cfca5d2d6838ac539563/AppSigner/MainView.swift#L682

Don't think that will happen but can't hurt hehe :)

Nicely done - thx.
