### ISSUE TITLE
Cannot open iOS app signer

### ISSUE THREAD

**Issue by mribeiro** [DanTheMan827/ios-app-signer#7]
I copy the .app (after extracting the zip file) to the /Applications folder.
When opening the first time, mac os warns me about the app not being from a certified developer, yada, yada... I press "Open".
App keeps bouncing in tray and never opens.

The same happens if I try to open the app outside of /Applications folder.

OS: 10.11.2
Xcode: 7.2 (7C68)

I have my own free and personal team and also enrolled on an enterprise team.
For both I have the dev certificates and provisional profiles setup.

Pls let me know if I can provide further information.

Thanks!

**Comment by DanTheMan827** [comment]
If you debug the app in Xcode does it seem to hang or crash anywhere?

**Comment by mribeiro** [comment]
Yeah... I should've done it in the first place :facepalm:

So, it seems it hangs on line 48 of ProvisioningProfile.swift: let taskOutput = NSTask().execute("/usr/bin/security", workingDirectory: nil, arguments: securityArgs)

if I run the command in the terminal with /usr/bin/security cms -D -i "/Users/aribeiro/Library/MobileDevice/Provisioning Profiles/0068be67-8b96-4096-a783-88fb3ca74fd5.mobileprovision" it gives me the output immediately.

However, I must say this provisioning profile if from that enterprise account I'm enrolled in and it gives 106KB of output (not sure if too much for this kind of operation or not, I'm not an Apple Developer expert).

Also, I tried running this "let taskOutput2 = NSTask().execute("/bin/ls", workingDirectory: nil, arguments: nil)" and worked well, just thought I could have something broken between Swift and Terminal (if that would even make sense).

Let me know if there's something else I can help with

**Comment by DanTheMan827** [comment]
I only have a free developer account so I definitely don't have access to
any provisioning profiles that are that large...

If you step into that line of code with the debugger how far does it get?

There shouldn't be an issue with the size of the file but there may be one
with how I read the command output

**Comment by mribeiro** [comment]
When trying to step into self.waitUntilExit I get the hang immediately, so I'm not even able to try to inspect what may be running over. Nevertheless, I tried to access its implementation but got only until its declaration, so I cannot see anything under the hood.

I was googling around and I found this http://www.raywenderlich.com/36537/nstask-tutorial . It seems that guy is reading the output of a terminal using Notifications, which may be safer than trying to get it all at once as it is done now. Just a wild guess!

**Comment by clementbarry** [comment]
Same here. sleep(2) also helped (thanks mribeiro!)

**Comment by DanTheMan827** [comment]
The issue appears to be the fact that the pipe can only take 8KB of data at a time and the process will hang until that buffer is flushed.

Provisioning profiles can get quite large and that is causing the hangs at launch for some people.

**Comment by benzer** [comment]
I am trying to run the iOS app signer and the app won't start for me too. Not sure what sleep2 is . could some one please explain simply how to get this app running?
El capitan 10.11.2

thanks

**Comment by mribeiro** [comment]
You need to check out the code, open it in Xcode, change it and run. If you're not familiar with development I don't advise you going thru this way . Better wait for a fix

**Comment by DanTheMan827** [comment]
Sorry about the wait, Christmas, New years and everything...

This problem should be fixed in r15

**Comment by mribeiro** [comment]
No apologizes necessary, after all you're doing us all a favour. Will test ASAP and and close of fixed :-)

**Comment by mribeiro** [comment]
All good! App can take a couple seconds to open (I have A LOT of prov profiles) but works flawlessly!
Good work! Thanks
:+1:

**Comment by benzer** [comment]
yes thanks! works now!

**Comment by mhussien84** [comment]
plz help me , i have problem with ios app signer 
<img width="442" alt="screen shot 2016-02-17 at 6 29 10 am" src="https://cloud.githubusercontent.com/assets/17304006/13127883/0e303d20-d5e3-11e5-9f52-f268d3ab3402.png">
<img width="587" alt="screen shot 2016-02-17 at 6 29 49 am" src="https://cloud.githubusercontent.com/assets/17304006/13127885/122dc79e-d5e3-11e5-84ba-2db9703f72b7.png">

**Comment by mribeiro** [comment]
@mhussien84 Do you have your developer certificate in Keychain?
