### ISSUE TITLE
No codesigning certificates found!

### ISSUE THREAD

**Issue by deeya20012002** [DanTheMan827/ios-app-signer#9]
iOS app signer v17 i have free dev. account

**Comment by PDCZERO** [comment]
I have the same problem with mine already unsintalled and reinstalled both app signer and Xcode

**Comment by DanTheMan827** [comment]
Apple expired some required intermediate certificates today (Feb, 14th)

You need to install the updated certificate

See https://developer.apple.com/support/certificates/expiration/

Basically, you need to install the [renewed certificate](https://developer.apple.com/certificationauthority/AppleWWDRCA.cer)
